### ISSUE TITLE
SD Maid stops responding and force closes

### ISSUE THREAD

**Issue by erfirya** [d4rken-org/sdmaid#5770] opened 2022-10-15 10:25 UTC
when I run sd maid it just freezes midway and force stops.

Install ID: d81bbe54-180a-4fa4-8d80-20767aa67ca3
Xiaomi POCO X3 NFC
xiaomi.eu MIUI 13 Android 12
SD Maid v5.5.1, Unlocker v4.5.0
Magisk v25.2

**Comment by smithbill17** [comment] 2022-10-15 13:39
I'm also on MIUI 13.0.5.0 and SD Maid hangs when Optimizing Databases (see attached image)
![Screenshot_2022-10-15-14-35-49-169_eu thedarken sdm](https://user-images.githubusercontent.com/66825587/195989495-ae2aaad2-f7db-4da1-b8de-126811abcada.jpg)

**Comment by erfirya** [comment] 2022-10-15 15:48
it only stops working if I turn off the 'skip running apps' on databases' settings. but if it's turned on, the process finishes successfully

**Comment by erfirya** [comment] 2022-10-15 15:52
and it freezes right when optimizing the exact same path "/data/user/0/eu.darken.sdm/databases/..." like @smithbill17's screenshot
![Screenshot_2022-10-15-23-41-59-701_eu thedarken sdm](https://user-images.githubusercontent.com/71990871/195995792-5b9f91c5-8852-4c54-865e-86c207d686cd.jpg)

**Comment by d4rken** [comment] 2022-10-16 10:17
Hm, I think this is a dupe of https://github.com/d4rken-org/sdmaid/issues/5768

Please try with the latest update.

**Closed** 2022-10-16 10:17 UTC
Labels: bug
