### ISSUE TITLE
Bug: App2SD should be disabled by default

### ISSUE THREAD

**Issue by mcl21014** [d4rken-org/sdmaid#4049] opened 2020-09-30 11:37 UTC
### What happened?
Try to run Databases tool with the new SDM on the SD Card.

### What did you expect to happen?
Databases tool runs without error.

### How can I reproduce the issue?
Get a device with app2sd support and move SDM to the SD card. Then, run the Databases tool.

### Comments
Please note this issue somewhere so users don't get upset.
### SD Maid
Version: `5.0.0 (50000)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/beyond2qlteue/beyond2q:10/QP1A.190711.020/G975U1UES4DTH3:user/release-keys`

**Comment by pak9813** [comment] 2021-03-11 22:10
Duplicate of #4701 https://github.com/d4rken/sdmaid-public/issues/4571#issue-800046834

**Closed** 2023-04-01 20:59 UTC
Labels: bug, c: Databases, api: 30-A11-R
