### ISSUE TITLE
Bug: After uninstalling an app, it still appears in AppControl.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#4254] opened 2020-11-13 15:12 UTC
### What happened?
После удаления приложения оно спустя полдня все равно продолжает отображаться в AppControl.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5537653/video.zip)

[sdmaid_logfile_1605279660595.txt.zip](https://github.com/d4rken/sdmaid-public/files/5537656/sdmaid_logfile_1605279660595.txt.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by Ingood5** [comment] 2020-11-13 15:17
После перезагрузки телефона приложение исчезло.

**Comment by d4rken** [comment] 2020-11-14 19:44
Was it a system application before?

Did you try to force-stop SD Maid, to see if it was a local cache issue in SD Maid?

**Comment by Ingood5** [comment] 2020-11-16 10:15
Приложение было не системное, установил несколько дней назад. Остановить приложение не пробовал. Установил приложение ещё раз, проблема не повторилась. Вы сможете понять причину ошибки по логу?

**Comment by Ingood5** [comment] 2020-11-23 04:01
Ошибка произошла ещё раз сразу с 6 приложениями, после принудительной остановки SD Maid проблема исчезла.

**Comment by d4rken** [comment] 2020-12-27 18:59
I think this may be a duplicate of #3879, I will do further research.

**Comment by MikeZeDev** [comment] 2022-04-17 11:25
Sorry for reviving this old report but i have the issue on Android 12. I use a stock Samsung ROM on this Samsung A51 that i rooted using magisk. I uninstalled some system apps using pm uninstall, they still show as installed but only in SDMaid. 

Other app like Appinspector/ Titanium / Alpha backup doesnt see them . Even the windows pc app "Unioversal Android Debloater" saw them as uninstalled.

If i uninstall them using SDMaid doesn't change anything. They are indeed "stopped" but still here after another SDmaid scan.

I know that there are some persistant app that come back like the infamous "samsung GOS" but its the first time i see that for applications like ANT+, Aremoji etc.. I dont know whats going on.

I cant read all that russian stuff sorry.

**Comment by d4rken** [comment] 2022-04-17 11:37
@MikeZeDev Make sure SD Maid is not working with old data, i.e. force stop SD Maid or reboot the device to check.

If you check the app details in AppControl, what paths does SD Maid show?

**Comment by MikeZeDev** [comment] 2022-04-17 12:25
I force stopped it, cleaned SDmaid cache and data, and rebooted the phone because i thought it was a caching issue.  I still have the problem.

I dont think its worth mentioning but previously this phone used to be on Android 11 (rooted too) and SDmaid had no problem uninstalling the same apps.


AR Doodle 
com.samsung.android.ardrawing

System - Frozen - stopped  (i frozen the problematic apps )

Path : 

/system/app/ARDrawing
/data/dalvik-cache/arm64
/system@app@ARDrawing@ARDrawing.apk@classes.dex
/system@app@ARDrawing@ARDrawing.apk@classes.vdex

Just uninstalled it using SDMaid, did another scan, app is still showing as System frozen Stopped BUT there is no path AND  "/system/app/ARDrawing" doesnt exist anymore ,

But the app it still listed.

**Comment by MikeZeDev** [comment] 2022-04-17 12:44
Folder is back after a reboot.

**Comment by d4rken** [comment] 2022-04-28 12:24
This is a system app, SD Maid has no chance of success without root here.
The system likely reads the pre-installed app package during boot which makes it reappear.

**Closed** 2023-04-01 20:49 UTC
Labels: c: AppControl
