### ISSUE TITLE
Sd Maid asking me to RE-nable Accessibility feature 

### ISSUE THREAD

**Issue by KawaiiRakker** [d4rken-org/sdmaid#4272] opened 2020-11-16 17:58 UTC
Sd Maid asking me to re-enable Accessibility feature the second time I run the cleaner
![Screenshot_2020-11-17-01-50-08-469_eu thedarken sdm](https://user-images.githubusercontent.com/74561061/99289694-3f698a80-2878-11eb-915e-85302a91ac9d.jpg)

**Comment by KawaiiRakker** [comment] 2020-11-16 18:00
When I try to re-enable the accessibility feature and restart the app, it still showing the same message

**Comment by d4rken** [comment] 2020-11-28 08:08
This usually means that the system things the service crashed and it will not launch it again. This is fixed by a reboot.
The question is why the system thinks the service has crashed. In some cases it's caused by SD Maid being killed by another app/gesture and that makes the system think the service has crashed.

**Comment by Rriggs95** [comment] 2020-12-24 07:22
This is still an issue, on at least on Android 10 with MIUI 12. Possibly due to the Security app, or some other pre installed MI app.

If that's the case, what would a solution be? Short of rooting your phone and removing all pre installed apps.
If it could be fixed on the developers end, what info would be necessary?

**Comment by d4rken** [comment] 2020-12-27 18:55
> This is still an issue, on at least on Android 10 with MIUI 12. Possibly due to the Security app, or some other pre installed MI app.

I currently don't have a solution for this, except recommend to exclude SD Maid from any such apps.

I can not stop the service to prevent this from my end, once I stop it in SD Maid, it has to be re-enabled by the user, so there is not much gain.

The only case where I could provide a solution, would be if this is happening due to a crash in SD Maid, but automatic reporting does not show anything like that.
So I would need instructions how on how to easily reproduce the issue on a local device to further investigate.

**Comment by dragonGod97677** [comment] 2021-06-20 16:14
That is normal, some phones just kills a accessibility service if the service is idle for a long time. I have a android 8.1 edition phone before, i have another app besides sd maid that uses accessibility service, native clipboard, and that service never gets killed, i always saw that sd maid service was the only get killed by android when after some reboot or OOM situation but native clipboard service is not killed

**Comment by COUPON4Vitamins** [comment] 2021-12-10 08:03
Same on 8.1 device never had any issues but on Android 9 the accessibility service gets killed when idle. It makes using Sd maid on Android 9 quite frustrating

**Comment by lawson85** [comment] 2022-10-08 23:16
Follow steps at dontkillmyapp.com to fix issues.

**Closed** 2023-04-01 20:48 UTC
Labels: c: AppCleaner, 0 needs info/repro
